plugins:
  post_approval_enabled:
    default: true
    client: true

  post_approval_badge:
    default: 0

  post_approval_redirect_enabled:
    default: true
    client: true
  post_approval_redirect_tl_max:
    default: 1
  post_approval_redirect_topic_group:
    default: "Post_Approval"
  post_approval_redirect_reply_group:
    default: "Post_Approval"
  post_approval_redirect_topic_prefix:
    default: "%s >"
    client: true
  post_approval_redirect_reply_prefix:
    default: "Reply to Topic >"
    client: true

  post_approval_redirect_reply_notice:
    default: "**This reply is awaiting review, please go [here](%URL%) for details.**"

  post_approval_redirect_only_first:
    default: false

  post_approval_button_enabled:
    default: true
    client: true
  post_approval_button_group:
    default: "Post_Approval"
    client: true

  post_approval_response_topic:
    default: "Thanks for your contribution! Your topic has been **approved** for **%CATEGORY%** here:\n%POST%"
  post_approval_response_reply:
    default: "Thanks for your contribution! Your post has been **approved** as **reply** to an existing topic here:\n%POST%"
  post_approval_response_badge:
    default: "🥇 Since you blazed through post approval, you got the **%BADGE%** badge for this post! Well done!"
  post_approval_response_topic_footer:
    default: "PS: You don't have to go through post approval for %CATEGORY%, so you can post there directly on your own in the future!"
  post_approval_response_reply_footer:
    default: "PS: You already have the required trust level to reply to this topic yourself, so you can post there directly on your own in the future without going through post approval!"
